from analisis import (
    load_and_filter_data,
    analyze_frequent_terms,
    plot_frequent_terms,
    analyze_retweets_vs_length,
    analyze_tweets_over_time,
    analyze_keywords_vs_retweets,
    analyze_retweet_distribution,
    create_markdown_report,
)

if __name__ == "__main__":
    # Ruta del archivo CSV
    file_path = "cyberpunk.csv"
    output_markdown = "informe.md"

    # Stopwords predefinidas
    stopwords = {
        "i",
        "me",
        "my",
        "myself",
        "we",
        "our",
        "ours",
        "ourselves",
        "you",
        "your",
        "yours",
        "yourself",
        "he",
        "him",
        "his",
        "himself",
        "she",
        "her",
        "hers",
        "herself",
        "it",
        "its",
        "itself",
        "they",
        "them",
        "their",
        "theirs",
        "themselves",
        "what",
        "which",
        "who",
        "whom",
        "this",
        "that",
        "these",
        "those",
        "am",
        "is",
        "are",
        "was",
        "were",
        "be",
        "been",
        "being",
        "have",
        "has",
        "had",
        "having",
        "do",
        "does",
        "did",
        "doing",
        "a",
        "an",
        "the",
        "and",
        "but",
        "if",
        "or",
        "because",
        "as",
        "until",
        "while",
        "of",
        "at",
        "by",
        "for",
        "with",
        "about",
        "against",
        "between",
        "into",
        "through",
        "during",
        "before",
        "after",
        "above",
        "below",
        "to",
        "from",
        "up",
        "down",
        "in",
        "out",
        "on",
        "off",
        "over",
        "under",
        "again",
        "further",
        "then",
        "once",
        "here",
        "there",
        "when",
        "where",
        "why",
        "how",
        "all",
        "any",
        "both",
        "each",
        "few",
        "more",
        "most",
        "other",
        "some",
        "such",
        "no",
        "nor",
        "not",
        "only",
        "own",
        "same",
        "so",
        "than",
        "too",
        "very",
        "s",
        "t",
        "can",
        "will",
        "just",
        "don",
        "should",
        "now",
    }

    # Cargar y procesar datos
    data = load_and_filter_data(file_path)

    # Analizar términos frecuentes
    term_counts = analyze_frequent_terms(data, "text", stopwords)

    # Graficar términos frecuentes
    plot_frequent_terms(term_counts)

    # Analizar relaciones adicionales
    analyze_retweets_vs_length(data)
    analyze_tweets_over_time(data)
    analyze_keywords_vs_retweets(data, ["cyberpunk", "2077", "game", "genshinimpact"])
    analyze_retweet_distribution(data)

    # Generar informe en Markdown
    additional_analyses = [
        ("Relación entre longitud del texto y retweets", "retweets_vs_length.png"),
        ("Cantidad de tuits a lo largo del tiempo", "tweets_over_time.png"),
        ("Promedio de retweets según palabras clave", "keywords_vs_retweets.png"),
        ("Distribución de retweets", "retweet_distribution.png"),
    ]
    create_markdown_report(file_path, term_counts, output_markdown, additional_analyses)

    print(f"Informe generado: {output_markdown}")
